[package]
name = "trigger-timer"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1"
clap = { version = "3.1.15", features = ["derive", "env"] }
futures = "0.3.25"
serde = "1.0"
spin-core = { version = "0.7.1", path = "../../crates/core" }
spin-trigger = { version = "0.7.1", path = "../../crates/trigger" }
tokio = { version = "1.11", features = [ "full" ] }
tokio-scoped = "0.2.0"

[dependencies.wit-bindgen-wasmtime]
git = "https://github.com/fermyon/wit-bindgen-backport"
rev = "a39003fadce6c7a8654e3e044fc39fc80d81ec7b"
features = ["async"]

[workspace]
