spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that exercises key-value storage."
name = "spin-key-value"
trigger = {type = "http", base = "/test"}
version = "1.0.0"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/spin_key_value.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
